import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

const html = await readFile(new URL('../public/index.html', import.meta.url), 'utf8');
const app = await readFile(new URL('../public/app.js', import.meta.url), 'utf8');
const css = await readFile(new URL('../public/styles.css', import.meta.url), 'utf8');

assert.match(html, /id="monitorRealDemoBtn"/);
assert.match(html, /id="realDemoMonitorSummary"/);
assert.match(html, /id="realDemoAcceptanceSummary"/);
assert.match(html, /进入真实等待状态/);
assert.match(html, /启动验收探针/);
assert.match(html, /恢复最近真实轴/);
assert.match(html, /登录飞书账号（妙记）/);
assert.match(html, /授权会议扫描兜底/);
assert.match(html, /id="larkMeetingScanLoginBtn"/);
assert.match(html, /id="timelineZoomOutBtn"/);
assert.match(html, /id="timelineFitBtn"/);
assert.match(html, /id="timelineZoomInBtn"/);
assert.match(html, /id="timelinePanInput"/);
assert.match(app, /\/api\/lark\/real-demo\/monitor/);
assert.match(app, /\/api\/lark\/restore-latest-real-meeting-axis/);
assert.match(app, /\/api\/lark\/real-demo\/progress/);
assert.match(app, /\/api\/lark\/real-demo\/acceptance/);
assert.match(app, /\/api\/lark\/real-demo\/progress-stream/);
assert.match(app, /const width = 1040/);
assert.match(app, /<svg viewBox="0 0 \$\{width\} \$\{height\}"/);
assert.match(app, /function zoomTimeline/);
assert.match(app, /function fitTimelineView/);
assert.match(app, /function panTimelineTo/);
assert.match(app, /visibleCalibratedSequence/);
assert.match(app, /SPEAKER_MERGE_GAP_MS/);
assert.match(app, /SPEAKER_REPEAT_FILTER_MS/);
assert.match(app, /speakerMarkers/);
assert.match(app, />发言人</);
assert.doesNotMatch(app, /segmentRects/);
assert.match(app, /function fmtLatency/);
assert.match(app, /function eventMarkerMeta/);
assert.match(app, /delivery_delay_ms/);
assert.doesNotMatch(app, /visualDurationMs \/ 1000 \* 2\.2/);
assert.match(css, /\.timeline svg\s*\{[\s\S]*width: 100%;[\s\S]*height: auto;/);
assert.match(css, /\.timeline-zoom-controls/);
assert.match(css, /\.timeline-window-controls/);
assert.match(app, /realDemoMonitorInFlight/);
assert.match(app, /realDemoProgress/);
assert.match(app, /realDemoAcceptance/);
assert.match(app, /realDemoProgressStream/);
assert.match(app, /completion_evidence/);
assert.match(app, /产品验收/);
assert.match(app, /严格事件投递/);
assert.match(app, /requirementSummary/);
assert.match(app, /完成验收：/);
assert.match(app, /建轴来源/);
assert.match(app, /飞书事件建轴/);
assert.match(app, /realAxisSourceLabel/);
assert.match(app, /renderDebugInputControls/);
assert.match(app, /axisSourceIsFallback/);
assert.match(app, /不是飞书 meeting_start 事件建轴/);
assert.match(app, /passive_scan: true/);
assert.match(app, /tenant_fallback_enabled: false/);
assert.match(app, /真实演示模式只等待飞书真实会议事件或当前用户会议扫描/);
assert.match(app, /不会建轴/);
assert.match(app, /不能用 probe\/pending\/按钮轴代替真实会议开始建轴/);
assert.match(app, /会后补传标注必须填写真实采集时间/);
assert.match(app, /查询这条标注是否 pending/);
assert.match(app, /curl -N/);
assert.match(app, /openAuthPopup/);
assert.match(app, /likelyNeedsAuth/);
assert.match(app, /vc:meeting\.search:read/);
assert.match(app, /recent_event_restore/);
assert.match(app, /刚刚投递的飞书会议开始事件恢复时间轴/);
assert.match(app, /实时建轴主路径不是这里登录拿权限/);
assert.match(app, /最近真实开始事件早于本次等待/);

console.log('ok real demo monitor UI control');
